### ISSUE TITLE
[AVM Module Issue]: Support v4 of azurerm

### ISSUE THREAD

**Issue by antoineozenne** [Azure/terraform-azurerm-avm-res-authorization-roleassignment#77]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.0

### Description

The versions of the providers are fixed (see in [required_providers](https://github.com/Azure/terraform-azurerm-avm-res-authorization-roleassignment/blob/0d5e7efe51445b2e9b296d4b396ca6b011baee34/terraform.tf#L6)) so we can't use this module with others because we can't use a newer version of a provider. According to the [Terraform doc](https://developer.hashicorp.com/terraform/language/modules/develop/providers#provider-aliases-within-modules):

> If you are writing a shared Terraform module, constrain only the minimum required provider version using a `>=` constraint. This should specify the minimum version containing the features your module relies on, and thus allow a user of your module to potentially select a newer provider version if other features are needed by other parts of their overall configuration.

Can you please change the constraint for each provider?

**Comment by jaredfholgate** [comment]
Hi @antoineozenne 

It is not as simple as the HashiCorp docs make out. How do you handle breaking changes between major versions of provider?

You can see we have our own standards around this here: https://azure.github.io/Azure-Verified-Modules/specs/terraform/#id-tfnfr26---category-code-style---providers-in-required_providers

You can also see our plans for v4 support here: https://github.com/Azure/Azure-Verified-Modules/discussions/1338

In the case of this particular module, our intention is to convert it to use `azapi` instead of `azurerm` prior to it going to version 1. That will allow us to utilise it better moving forward and have less issues like this.

I don't have a timescale for this yet, but we can look to see if it will work with v4 of `azurerm` in the short term.

**Comment by But4ler** [comment]
Thanks for the feedback
Quite a few other avm modules follow the same 2-step strategy, first azurerm 4 (which suits most people I think) and then a more technical overhaul to azapi.

We currently use 9 AVM modules, but version management between modules is a real problem and is blocking us in v3

**Comment by tobiasehlert** [comment]
@jaredfholgate, created PR #83 so we can resolve this issue :)

**Comment by jaredfholgate** [comment]
Released in https://github.com/Azure/terraform-azurerm-avm-res-authorization-roleassignment/releases/tag/v0.2.0

**Comment by antoineozenne** [comment]
@jaredfholgate Thank you for the update! Is it possible to do the same thing with azuread (allow using v3 instead of force using v2.46)?
